CREATE TABLE essays (
    projectid text                       -- Example: NULL,
    teacher_acctid text                  -- Example: NULL,
    title text                           -- Example: NULL,
    short_description text               -- Example: NULL,
    need_statement text                  -- Example: NULL,
    essay text                           -- Example: NULL
);

CREATE TABLE projects (
    projectid text PRIMARY KEY           -- Example: NULL,
    teacher_acctid text                  -- Example: NULL,
    schoolid text                        -- Example: NULL,
    school_ncesid text                   -- Example: NULL,
    school_latitude real                 -- Example: NULL,
    school_longitude real                -- Example: NULL,
    school_city text                     -- Example: NULL,
    school_state text                    -- Example: NULL,
    school_zip integer                   -- Example: NULL,
    school_metro text                    -- Example: NULL,
    school_district text                 -- Example: NULL,
    school_county text                   -- Example: NULL,
    school_charter text                  -- Example: NULL,
    school_magnet text                   -- Example: NULL,
    school_year_round text               -- Example: NULL,
    school_nlns text                     -- Example: NULL,
    school_kipp text                     -- Example: NULL,
    school_charter_ready_promise text    -- Example: NULL,
    teacher_prefix text                  -- Example: NULL,
    teacher_teach_for_america text       -- Example: NULL,
    teacher_ny_teaching_fellow text      -- Example: NULL,
    primary_focus_subject text           -- Example: NULL,
    primary_focus_area text              -- Example: NULL,
    secondary_focus_subject text         -- Example: NULL,
    secondary_focus_area text            -- Example: NULL,
    resource_type text                   -- Example: NULL,
    poverty_level text                   -- Example: NULL,
    grade_level text                     -- Example: NULL,
    fulfillment_labor_materials real     -- Example: NULL,
    total_price_excluding_optional_support real -- Example: NULL,
    total_price_including_optional_support real -- Example: NULL,
    students_reached integer             -- Example: NULL,
    eligible_double_your_impact_match text -- Example: NULL,
    eligible_almost_home_match text      -- Example: NULL,
    date_posted date                     -- Example: NULL
);

CREATE TABLE donations (
    donationid text PRIMARY KEY          -- Example: '000000a91a14ed37bef82e125c102e77',
    projectid text                       -- Example: '00001ccc0e81598c4bd86bacb94d7acb',
    donor_acctid text                    -- Example: '000013be53ed7382ed5d5975eb86eb85',
    donor_city text                      -- Example: 'Peachtree City',
    donor_state text                     -- Example: 'GA',
    donor_zip text                       -- Example: '0',
    is_teacher_acct text                 -- Example: 'f',
    donation_timestamp datetime          -- Example: '2000-03-01 14:24:26',
    donation_to_project real             -- Example: 42.5,
    donation_optional_support real       -- Example: 7.5,
    donation_total real                  -- Example: -15.0,
    dollar_amount text                   -- Example: '10_to_100',
    donation_included_optional_support text -- Example: 't',
    payment_method text                  -- Example: 'no_cash_received',
    payment_included_acct_credit text    -- Example: 'f',
    payment_included_campaign_gift_card text -- Example: 't',
    payment_included_web_purchased_gift_card text -- Example: 'f',
    payment_was_promo_matched text       -- Example: 'f',
    via_giving_page text                 -- Example: 'f',
    for_honoree text                     -- Example: 'f',
    donation_message text                -- Example: 'I gave to this project because I support the efforts of this teacher with each o',
    FOREIGN KEY (projectid) REFERENCES projects(projectid)
);

CREATE TABLE resources (
    resourceid text PRIMARY KEY          -- Example: '0000037fecc4461faf0e49328ae66661',
    projectid text                       -- Example: '00001ccc0e81598c4bd86bacb94d7acb',
    vendorid integer                     -- Example: 430,
    vendor_name text                     -- Example: '100 % Educational Videos',
    project_resource_type text           -- Example: 'Technology',
    item_name text                       -- Example: 'iPod nano 4th Gen 8GB (Black)',
    item_number text                     -- Example: '249995.001',
    item_unit_price real                 -- Example: 149.0,
    item_quantity integer                -- Example: 0,
    FOREIGN KEY (projectid) REFERENCES projects(projectid)
);