CREATE TABLE awards_players (
    playerID text                        -- Example: 'abdulka01',
    award text                           -- Example: 'All-Defensive Second Team',
    year integer                         -- Example: 1969,
    lgID text                            -- Example: 'NBA',
    note text                            -- Example: 'tie',
    pos text                             -- Example: 'C',
    PRIMARY KEY (playerID, award, year),
    FOREIGN KEY (playerID) REFERENCES players(playerID)
);

CREATE TABLE coaches (
    coachID text                         -- Example: 'adelmri01',
    year integer                         -- Example: 1988,
    tmID text                            -- Example: 'POR',
    lgID text                            -- Example: 'NBA',
    stint integer                        -- Example: 2,
    won integer                          -- Example: 14,
    lost integer                         -- Example: 21,
    post_wins integer                    -- Example: 0,
    post_losses integer                  -- Example: 3,
    PRIMARY KEY (coachID, year, tmID, stint),
    FOREIGN KEY (tmID) REFERENCES teams(tmID),
    FOREIGN KEY (year) REFERENCES teams(year)
);

CREATE TABLE draft (
    id integer PRIMARY KEY               -- Example: 1,
    draftYear integer                    -- Example: 1967,
    draftRound integer                   -- Example: 0,
    draftSelection integer               -- Example: 0,
    draftOverall integer                 -- Example: 0,
    tmID text                            -- Example: 'ANA',
    firstName text                       -- Example: 'Darrell',
    lastName text                        -- Example: 'Hardy',
    suffixName text                      -- Example: 'Jr.',
    playerID text                        -- Example: 'hardyda01',
    draftFrom text                       -- Example: 'Baylor',
    lgID text                            -- Example: 'ABA',
    FOREIGN KEY (tmID) REFERENCES teams(tmID),
    FOREIGN KEY (draftYear) REFERENCES teams(year)
);

CREATE TABLE player_allstar (
    playerID text                        -- Example: 'abdulka01',
    last_name text                       -- Example: 'Abdul-Jabbar',
    first_name text                      -- Example: 'Kareem',
    season_id integer                    -- Example: 1969,
    conference text                      -- Example: 'East',
    league_id text                       -- Example: 'NBA',
    games_played integer                 -- Example: 1,
    minutes integer                      -- Example: 18,
    points integer                       -- Example: 10,
    o_rebounds integer                   -- Example: 1,
    d_rebounds integer                   -- Example: 2,
    rebounds integer                     -- Example: 11,
    assists integer                      -- Example: 4,
    steals integer                       -- Example: 3,
    blocks integer                       -- Example: 2,
    turnovers integer                    -- Example: 1,
    personal_fouls integer               -- Example: 3,
    fg_attempted integer                 -- Example: 8,
    fg_made integer                      -- Example: 4,
    ft_attempted integer                 -- Example: 2,
    ft_made integer                      -- Example: 2,
    three_attempted integer              -- Example: 0,
    three_made integer                   -- Example: 0,
    PRIMARY KEY (playerID, season_id),
    FOREIGN KEY (playerID) REFERENCES players(playerID)
);

CREATE TABLE players (
    playerID text PRIMARY KEY            -- Example: 'abdelal01',
    useFirst text                        -- Example: 'Alaa',
    firstName text                       -- Example: 'Alaa',
    middleName text                      -- Example: 'Shareef',
    lastName text                        -- Example: 'Abdelnaby',
    nameGiven text                       -- Example: 'nameGiven',
    fullGivenName text                   -- Example: 'Ferdinand Lewis Alcindor, Jr.',
    nameSuffix text                      -- Example: 'Jr.',
    nameNick text                        -- Example: 'Lew, Cap',
    pos text                             -- Example: 'F-C',
    firstseason integer                  -- Example: 0,
    lastseason integer                   -- Example: 0,
    height real                          -- Example: 82.0,
    weight integer                       -- Example: 240,
    college text                         -- Example: 'Duke',
    collegeOther text                    -- Example: 'Santa Monica City',
    birthDate date                       -- Example: '1968-06-24',
    birthCity text                       -- Example: 'Cairo',
    birthState text                      -- Example: 'NY',
    birthCountry text                    -- Example: 'EGY',
    highSchool text                      -- Example: 'Bloomfield Senior',
    hsCity text                          -- Example: 'Bloomfield',
    hsState text                         -- Example: 'NJ',
    hsCountry text                       -- Example: 'USA',
    deathDate date                       -- Example: '0000-00-00',
    race text                            -- Example: 'B'
);

CREATE TABLE teams (
    year integer                         -- Example: 1937,
    lgID text                            -- Example: 'NBL',
    tmID text                            -- Example: 'AFS',
    franchID text                        -- Example: 'AFS',
    confID text                          -- Example: 'EC',
    divID text                           -- Example: 'EA',
    rank integer                         -- Example: 1,
    confRank integer                     -- Example: 0,
    playoff text                         -- Example: 'CF',
    name text                            -- Example: 'Akron Firestone Non-Skids',
    o_fgm integer                        -- Example: 249,
    o_ftm integer                        -- Example: 183,
    o_pts integer                        -- Example: 681,
    d_pts integer                        -- Example: 578,
    homeWon integer                      -- Example: 8,
    homeLost integer                     -- Example: 1,
    awayWon integer                      -- Example: 5,
    awayLost integer                     -- Example: 3,
    won integer                          -- Example: 14,
    lost integer                         -- Example: 4,
    games integer                        -- Example: 18,
    arena text                           -- Example: 'Boston Garden',
    PRIMARY KEY (year, tmID)
);

CREATE TABLE awards_coaches (
    id integer PRIMARY KEY               -- Example: 1,
    year integer                         -- Example: 1962,
    coachID text                         -- Example: 'gallaha01',
    award text                           -- Example: 'NBA Coach of the Year',
    lgID text                            -- Example: 'NBA',
    note text                            -- Example: 'tie',
    FOREIGN KEY (coachID) REFERENCES coaches(coachID),
    FOREIGN KEY (year) REFERENCES coaches(year)
);

CREATE TABLE players_teams (
    id integer PRIMARY KEY               -- Example: 1,
    playerID text                        -- Example: 'abdelal01',
    year integer                         -- Example: 1990,
    stint integer                        -- Example: 1,
    tmID text                            -- Example: 'POR',
    lgID text                            -- Example: 'NBA',
    GP integer                           -- Example: 43,
    GS integer                           -- Example: 0,
    minutes integer                      -- Example: 290,
    points integer                       -- Example: 135,
    oRebounds integer                    -- Example: 27,
    dRebounds integer                    -- Example: 62,
    rebounds integer                     -- Example: 89,
    assists integer                      -- Example: 12,
    steals integer                       -- Example: 4,
    blocks integer                       -- Example: 12,
    turnovers integer                    -- Example: 22,
    PF integer                           -- Example: 39,
    fgAttempted integer                  -- Example: 116,
    fgMade integer                       -- Example: 55,
    ftAttempted integer                  -- Example: 44,
    ftMade integer                       -- Example: 25,
    threeAttempted integer               -- Example: 0,
    threeMade integer                    -- Example: 0,
    PostGP integer                       -- Example: 5,
    PostGS integer                       -- Example: 0,
    PostMinutes integer                  -- Example: 13,
    PostPoints integer                   -- Example: 4,
    PostoRebounds integer                -- Example: 1,
    PostdRebounds integer                -- Example: 2,
    PostRebounds integer                 -- Example: 3,
    PostAssists integer                  -- Example: 0,
    PostSteals integer                   -- Example: 0,
    PostBlocks integer                   -- Example: 0,
    PostTurnovers integer                -- Example: 0,
    PostPF integer                       -- Example: 0,
    PostfgAttempted integer              -- Example: 6,
    PostfgMade integer                   -- Example: 2,
    PostftAttempted integer              -- Example: 0,
    PostftMade integer                   -- Example: 0,
    PostthreeAttempted integer           -- Example: 0,
    PostthreeMade integer                -- Example: 0,
    note text                            -- Example: 'C',
    FOREIGN KEY (tmID) REFERENCES teams(tmID),
    FOREIGN KEY (year) REFERENCES teams(year)
);

CREATE TABLE series_post (
    id integer PRIMARY KEY               -- Example: 1,
    year integer                         -- Example: 1946,
    round text                           -- Example: 'F',
    series text                          -- Example: 'O',
    tmIDWinner text                      -- Example: 'PHW',
    lgIDWinner text                      -- Example: 'NBA',
    tmIDLoser text                       -- Example: 'CHS',
    lgIDLoser text                       -- Example: 'NBA',
    W integer                            -- Example: 4,
    L integer                            -- Example: 1,
    FOREIGN KEY (tmIDLoser) REFERENCES teams(tmID),
    FOREIGN KEY (year) REFERENCES teams(year),
    FOREIGN KEY (tmIDWinner) REFERENCES teams(tmID),
    FOREIGN KEY (year) REFERENCES teams(year)
);