CREATE TABLE institution_details (
    unitid integer PRIMARY KEY           -- Example: 100654,
    chronname text                       -- Example: 'Alabama A&M University',
    city text                            -- Example: 'Normal',
    state text                           -- Example: 'Alabama',
    level text                           -- Example: '4-year',
    control text                         -- Example: 'Private for-profit',
    basic text                           -- Example: 'Masters Colleges and Universities--larger programs',
    hbcu text                            -- Example: 'X',
    flagship text                        -- Example: 'NULL',
    long_x real                          -- Example: -86.568502,
    lat_y real                           -- Example: 34.783368,
    site text                            -- Example: 'www.aamu.edu/',
    student_count integer                -- Example: 4051,
    awards_per_value real                -- Example: 14.2,
    awards_per_state_value real          -- Example: 18.8,
    awards_per_natl_value real           -- Example: 21.5,
    exp_award_value integer              -- Example: 105331,
    exp_award_state_value integer        -- Example: 75743,
    exp_award_natl_value integer         -- Example: 66436,
    exp_award_percentile integer         -- Example: 90,
    ft_pct real                          -- Example: 93.8,
    fte_value integer                    -- Example: 3906,
    fte_percentile integer               -- Example: 33,
    med_sat_value text                   -- Example: '823',
    med_sat_percentile text              -- Example: '0',
    aid_value integer                    -- Example: 7142,
    aid_percentile integer               -- Example: 72,
    endow_value text                     -- Example: 'NULL',
    endow_percentile text                -- Example: 'NULL',
    grad_100_value real                  -- Example: 10.0,
    grad_100_percentile integer          -- Example: 15,
    grad_150_value real                  -- Example: 29.1,
    grad_150_percentile integer          -- Example: 14,
    pell_value real                      -- Example: 71.2,
    pell_percentile integer              -- Example: 98,
    retain_value real                    -- Example: 63.1,
    retain_percentile integer            -- Example: 17,
    ft_fac_value real                    -- Example: 82.8,
    ft_fac_percentile integer            -- Example: 89,
    vsa_year text                        -- Example: '2010',
    vsa_grad_after4_first text           -- Example: '14.7',
    vsa_grad_elsewhere_after4_first text -- Example: '2',
    vsa_enroll_after4_first text         -- Example: '36.5',
    vsa_enroll_elsewhere_after4_first text -- Example: '16.1',
    vsa_grad_after6_first text           -- Example: '33',
    vsa_grad_elsewhere_after6_first text -- Example: '5.3',
    vsa_enroll_after6_first text         -- Example: '12.5',
    vsa_enroll_elsewhere_after6_first text -- Example: '14.6',
    vsa_grad_after4_transfer text        -- Example: '15.7',
    vsa_grad_elsewhere_after4_transfer text -- Example: '1.5',
    vsa_enroll_after4_transfer text      -- Example: '40.9',
    vsa_enroll_elsewhere_after4_transfer text -- Example: '17.2',
    vsa_grad_after6_transfer text        -- Example: '36.4',
    vsa_grad_elsewhere_after6_transfer text -- Example: '5.6',
    vsa_enroll_after6_transfer text      -- Example: '17.2',
    vsa_enroll_elsewhere_after6_transfer text -- Example: '11.1',
    similar text                         -- Example: '232937|100724|405997|113607|139533|144005|228501|101480|131876|144759|419509|176',
    state_sector_ct integer              -- Example: 13,
    carnegie_ct integer                  -- Example: 386,
    counted_pct text                     -- Example: '99.7|07',
    nicknames text                       -- Example: 'NULL',
    cohort_size integer                  -- Example: 882
);

CREATE TABLE institution_grads (
    unitid integer                       -- Example: 100654,
    year integer                         -- Example: 2011,
    gender text                          -- Example: 'B',
    race text                            -- Example: 'X',
    cohort text                          -- Example: '2y all',
    grad_cohort text                     -- Example: '446',
    grad_100 text                        -- Example: '73',
    grad_150 text                        -- Example: '105',
    grad_100_rate text                   -- Example: '16.4',
    grad_150_rate text                   -- Example: '23.5',
    FOREIGN KEY (unitid) REFERENCES institution_details(unitid)
);

CREATE TABLE state_sector_grads (
    stateid integer                      -- Example: 1,
    state text                           -- Example: 'Alabama',
    state_abbr text                      -- Example: 'AL',
    control text                         -- Example: 'Private for-profit',
    level text                           -- Example: '4-year',
    year integer                         -- Example: 2011,
    gender text                          -- Example: 'B',
    race text                            -- Example: 'A',
    cohort text                          -- Example: '4y bach',
    grad_cohort text                     -- Example: '0',
    grad_100 text                        -- Example: '0',
    grad_150 text                        -- Example: '0',
    grad_100_rate text                   -- Example: 'NULL',
    grad_150_rate text                   -- Example: 'NULL',
    grad_cohort_ct integer               -- Example: 9,
    FOREIGN KEY (stateid) REFERENCES state_sector_details(stateid),
    FOREIGN KEY (state) REFERENCES institution_details(state)
);

CREATE TABLE state_sector_details (
    stateid integer                      -- Example: 0,
    state text                           -- Example: 'United States',
    state_post text                      -- Example: 'U.S.',
    level text                           -- Example: '2-year',
    control text                         -- Example: 'Private for-profit',
    schools_count integer                -- Example: 632,
    counted_pct text                     -- Example: 'NULL',
    awards_per_state_value text          -- Example: 'NULL',
    awards_per_natl_value real           -- Example: 21.5,
    exp_award_state_value text           -- Example: 'NULL',
    exp_award_natl_value integer         -- Example: 66436,
    state_appr_value text                -- Example: 'NULL',
    state_appr_rank text                 -- Example: 'NULL',
    grad_rate_rank text                  -- Example: '23',
    awards_per_rank text                 -- Example: 'NULL',
    PRIMARY KEY (stateid, level, control),
    FOREIGN KEY (state) REFERENCES institution_details(state)
);