CREATE TABLE current (
    ballotpedia_id text                  -- Example: 'Sherrod Brown',
    bioguide_id text                     -- Example: 'A000055',
    birthday_bio date                    -- Example: '1952-11-09',
    cspan_id real                        -- Example: 45516.0,
    fec_id text                          -- Example: '['H2OH13033', 'S6OH00163']',
    first_name text                      -- Example: 'Sherrod',
    gender_bio text                      -- Example: 'M',
    google_entity_id_id text             -- Example: 'kg:/m/034s80',
    govtrack_id integer                  -- Example: 400050,
    house_history_id real                -- Example: 9996.0,
    icpsr_id real                        -- Example: 29389.0,
    last_name text                       -- Example: 'Brown',
    lis_id text                          -- Example: 'S307',
    maplight_id real                     -- Example: 168.0,
    middle_name text                     -- Example: 'L.',
    nickname_name text                   -- Example: 'Bob',
    official_full_name text              -- Example: 'Sherrod Brown',
    opensecrets_id text                  -- Example: 'N00003535',
    religion_bio text                    -- Example: 'Lutheran',
    suffix_name text                     -- Example: 'Jr.',
    thomas_id integer                    -- Example: 136,
    votesmart_id real                    -- Example: 27018.0,
    wikidata_id text                     -- Example: 'Q381880',
    wikipedia_id text                    -- Example: 'Sherrod Brown',
    PRIMARY KEY (bioguide_id, cspan_id)
);

CREATE TABLE current_terms (
    address text                         -- Example: NULL,
    bioguide text                        -- Example: NULL,
    caucus text                          -- Example: NULL,
    chamber text                         -- Example: NULL,
    class real                           -- Example: NULL,
    contact_form text                    -- Example: NULL,
    district real                        -- Example: NULL,
    end text                             -- Example: NULL,
    fax text                             -- Example: NULL,
    last text                            -- Example: NULL,
    name text                            -- Example: NULL,
    office text                          -- Example: NULL,
    party text                           -- Example: NULL,
    party_affiliations text              -- Example: NULL,
    phone text                           -- Example: NULL,
    relation text                        -- Example: NULL,
    rss_url text                         -- Example: NULL,
    start text                           -- Example: NULL,
    state text                           -- Example: NULL,
    state_rank text                      -- Example: NULL,
    title text                           -- Example: NULL,
    type text                            -- Example: NULL,
    url text                             -- Example: NULL,
    PRIMARY KEY (bioguide, end),
    FOREIGN KEY (bioguide) REFERENCES current(bioguide_id)
);

CREATE TABLE historical (
    ballotpedia_id text                  -- Example: 'Mo Cowan',
    bioguide_id text PRIMARY KEY         -- Example: 'A000001',
    bioguide_previous_id text            -- Example: '['F000246']',
    birthday_bio text                    -- Example: '1745-04-02',
    cspan_id text                        -- Example: '12590.0',
    fec_id text                          -- Example: '['S6CO00168']',
    first_name text                      -- Example: 'Richard',
    gender_bio text                      -- Example: 'M',
    google_entity_id_id text             -- Example: 'kg:/m/02pz46',
    govtrack_id integer                  -- Example: 401222,
    house_history_alternate_id text      -- Example: '13283.0',
    house_history_id real                -- Example: 9479.0,
    icpsr_id real                        -- Example: 507.0,
    last_name text                       -- Example: 'Bassett',
    lis_id text                          -- Example: 'S134',
    maplight_id text                     -- Example: '232.0',
    middle_name text                     -- Example: 'Samuel',
    nickname_name text                   -- Example: 'of Carrollton',
    official_full_name text              -- Example: 'Enid Greene Waldholtz',
    opensecrets_id text                  -- Example: 'N00008333',
    religion_bio text                    -- Example: 'Baptist',
    suffix_name text                     -- Example: 'Jr.',
    thomas_id text                       -- Example: '01308',
    votesmart_id text                    -- Example: '52156.0',
    wikidata_id text                     -- Example: 'Q518823',
    wikipedia_id text                    -- Example: 'Richard Bassett (politician)'
);

CREATE TABLE historical-terms (
    address text                         -- Example: '248 RUSSELL SENATE OFFICE BUILDING WASHINGTON DC 20510',
    bioguide text PRIMARY KEY            -- Example: 'A000001',
    chamber text                         -- Example: 'house',
    class real                           -- Example: 2.0,
    contact_form text                    -- Example: 'http://www.webb.senate.gov/contact.cfm',
    district real                        -- Example: 9.0,
    end text                             -- Example: '1793-03-03',
    fax text                             -- Example: '202-228-6363',
    last text                            -- Example: 'Levy',
    middle text                          -- Example: NULL,
    name text                            -- Example: NULL,
    office text                          -- Example: '248 Russell Senate Office Building',
    party text                           -- Example: 'Anti-Administration',
    party_affiliations text              -- Example: '{'start': '2009-01-06', 'end': '2009-12-22', 'party': 'Democrat'}',
    phone text                           -- Example: '202-224-4024',
    relation text                        -- Example: NULL,
    rss_url text                         -- Example: 'http://radel.house.gov/news/rss.aspx',
    start text                           -- Example: '1789-03-04',
    state text                           -- Example: 'DE',
    state_rank text                      -- Example: 'junior',
    title text                           -- Example: 'Majority Leader',
    type text                            -- Example: 'sen',
    url text                             -- Example: 'http://edwards.senate.gov/',
    FOREIGN KEY (bioguide) REFERENCES historical(bioguide_id)
);

CREATE TABLE social_media_new (
    bioguide text PRIMARY KEY            -- Example: NULL,
    facebook text                        -- Example: NULL,
    facebook_id real                     -- Example: NULL,
    govtrack real                        -- Example: NULL,
    instagram text                       -- Example: NULL,
    instagram_id real                    -- Example: NULL,
    thomas integer                       -- Example: NULL,
    twitter text                         -- Example: NULL,
    twitter_id real                      -- Example: NULL,
    youtube text                         -- Example: NULL,
    youtube_id text                      -- Example: NULL,
    FOREIGN KEY (bioguide) REFERENCES current(bioguide_id)
);